matrix:
  - mpi_on
  - mpi_off

mpi_on:
  build:
    modules:
      - ninja
    modules_package:
      - atlas:fftw,eigen,openmpi
      - eckit:openmpi
    dependencies:
      - ecmwf/ecbuild@develop
      - ecmwf/eckit@develop
      - ecmwf/fckit@develop
      - ecmwf/atlas@develop
    parallel: 64
    ntasks: 16
    env:
        - ATLAS_ORCA_CACHING=1
        - CTEST_PARALLEL_LEVEL=1
        - AUTO_LOAD_PLUGINS=1        
mpi_off:
  build:
    modules:
      - ninja
    modules_package:
      - atlas:fftw,eigen
    dependencies:
      - ecmwf/ecbuild@develop
      - ecmwf/eckit@develop
      - ecmwf/fckit@develop
      - ecmwf/atlas@develop
    parallel: 64
    env:
        - ATLAS_ORCA_CACHING=1
        - CTEST_PARALLEL_LEVEL=1
        - AUTO_LOAD_PLUGINS=1        


